name: 🧹 Lint Commit Messages

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: ⎔ Setup Node.js with Cache
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧹 Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
